export const LOGIN_DISPLAY_TOGGLE = 'LOGIN_DISPLAY_TOGGLE';

export const SIGNUP_DISPLAY_TOGGLE = 'SIGNUP_DISPLAY_TOGGLE';

export const FEED_DISPLAY_TOGGLE = 'FEED_DISPLAY_TOGGLE';

export const ADD_LISTING_TOGGLE = 'ADD_LISTING_TOGGLE';

export const USER_ITEMS_DISPLAY_TOGGLE = 'USER_ITEMS_DISPLAY_TOGGLE';

export const BARTER_DISPLAY_TOGGLE = 'BARTER_DISPLAY_TOGGLE';

// export const IS_LOGGED_IN = 'IS_LOGGED_IN';

export const CURRENT_USER = 'CURRENT_USER';

